-- Complete DentCare schema for fresh MySQL installations.
-- Definitions are intentionally idempotent so Flyway can adopt databases that
-- were initialized with the original manual scripts.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(60) NOT NULL,
    last_name VARCHAR(60) NOT NULL,
    phone VARCHAR(25),
    role VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('ADMINISTRATOR', 'RECEPTIONIST', 'DENTIST', 'DENTAL_ASSISTANT', 'PATIENT')),
    KEY idx_users_role (role),
    KEY idx_users_active (active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    item_code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(100) NOT NULL,
    unit VARCHAR(50) NOT NULL,
    reorder_level INT NOT NULL,
    current_quantity INT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    default_supplier_reference VARCHAR(150),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uk_inventory_items_code UNIQUE (item_code),
    CONSTRAINT chk_inventory_items_reorder CHECK (reorder_level >= 0),
    CONSTRAINT chk_inventory_items_quantity CHECK (current_quantity >= 0),
    KEY idx_inventory_items_category (category),
    KEY idx_inventory_items_active (active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_batches (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    inventory_item_id BIGINT NOT NULL,
    batch_number VARCHAR(100) NULL,
    expiry_date DATE NULL,
    quantity_on_hand INT NOT NULL DEFAULT 0,
    received_date DATE NULL,
    supplier_reference VARCHAR(150) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_batches_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (id),
    CONSTRAINT chk_inventory_batches_qty CHECK (quantity_on_hand >= 0),
    CONSTRAINT uk_inventory_batches_item_batch UNIQUE (inventory_item_id, batch_number),
    KEY idx_inventory_batches_item (inventory_item_id),
    KEY idx_inventory_batches_expiry (expiry_date),
    KEY idx_inventory_batches_qty (quantity_on_hand)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stock_movements (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    inventory_item_id BIGINT NOT NULL,
    inventory_batch_id BIGINT NULL,
    movement_type VARCHAR(20) NOT NULL,
    adjustment_direction VARCHAR(10) NULL,
    quantity INT NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    reason VARCHAR(255),
    responsible_user_id BIGINT NOT NULL,
    reversal_of_movement_id BIGINT,
    treatment_procedure_id BIGINT,
    batch_number VARCHAR(100),
    expiry_date DATE,
    CONSTRAINT fk_stock_movements_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (id),
    CONSTRAINT fk_stock_movements_batch FOREIGN KEY (inventory_batch_id) REFERENCES inventory_batches (id),
    CONSTRAINT uk_stock_movements_reversal UNIQUE (reversal_of_movement_id),
    CONSTRAINT chk_stock_movements_qty CHECK (quantity > 0),
    CONSTRAINT chk_stock_movements_type CHECK (movement_type IN ('RECEIVED', 'USED', 'DAMAGED', 'ADJUSTED', 'EXPIRED')),
    CONSTRAINT chk_stock_movements_adj_dir CHECK (adjustment_direction IS NULL OR adjustment_direction IN ('INCREASE', 'DECREASE')),
    KEY idx_stock_movements_item_time (inventory_item_id, occurred_at DESC),
    KEY idx_stock_movements_type (movement_type),
    KEY idx_stock_movements_user (responsible_user_id),
    KEY idx_stock_movements_expiry (expiry_date),
    KEY idx_stock_movements_batch (inventory_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS clinical_examinations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    dentist_id BIGINT NOT NULL,
    recorded_by_user_id BIGINT NOT NULL,
    appointment_id BIGINT NULL,
    examination_date DATE NOT NULL,
    chief_complaint TEXT NOT NULL,
    clinical_observations TEXT NULL,
    provisional_diagnosis VARCHAR(500) NULL,
    confirmed_diagnosis VARCHAR(500) NULL,
    is_diagnosis_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    confirmed_by_dentist_id BIGINT NULL,
    diagnosis_confirmed_at TIMESTAMP NULL,
    follow_up_date DATE NULL,
    follow_up_notes VARCHAR(500) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_clinical_examinations_patient FOREIGN KEY (patient_id) REFERENCES users (id),
    CONSTRAINT fk_clinical_examinations_dentist FOREIGN KEY (dentist_id) REFERENCES users (id),
    CONSTRAINT fk_clinical_examinations_recorded_by FOREIGN KEY (recorded_by_user_id) REFERENCES users (id),
    CONSTRAINT fk_clinical_examinations_confirmed_by FOREIGN KEY (confirmed_by_dentist_id) REFERENCES users (id),
    CONSTRAINT chk_clinical_examinations_status CHECK (status IN ('DRAFT', 'COMPLETED', 'CANCELLED')),
    KEY idx_clinical_examinations_patient (patient_id),
    KEY idx_clinical_examinations_dentist (dentist_id),
    KEY idx_clinical_examinations_date (examination_date),
    KEY idx_clinical_examinations_appointment (appointment_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tooth_findings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    examination_id BIGINT NOT NULL,
    tooth_number INT NULL,
    is_general BOOLEAN NOT NULL DEFAULT FALSE,
    condition_name VARCHAR(150) NOT NULL,
    notes VARCHAR(500) NULL,
    recorded_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tooth_findings_exam FOREIGN KEY (examination_id) REFERENCES clinical_examinations (id),
    CONSTRAINT fk_tooth_findings_recorded_by FOREIGN KEY (recorded_by_user_id) REFERENCES users (id),
    CONSTRAINT chk_tooth_findings_general_tooth CHECK ((is_general = TRUE AND tooth_number IS NULL) OR (is_general = FALSE AND tooth_number IS NOT NULL)),
    CONSTRAINT chk_tooth_findings_fdi CHECK (tooth_number IS NULL OR tooth_number BETWEEN 11 AND 18 OR tooth_number BETWEEN 21 AND 28 OR tooth_number BETWEEN 31 AND 38 OR tooth_number BETWEEN 41 AND 48 OR tooth_number BETWEEN 51 AND 55 OR tooth_number BETWEEN 61 AND 65 OR tooth_number BETWEEN 71 AND 75 OR tooth_number BETWEEN 81 AND 85),
    KEY idx_tooth_findings_exam (examination_id),
    KEY idx_tooth_findings_tooth (tooth_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS treatment_plans (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    dentist_id BIGINT NOT NULL,
    examination_id BIGINT NULL,
    created_by_user_id BIGINT NOT NULL,
    plan_name VARCHAR(150) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PROPOSED',
    total_estimated_cost DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    total_actual_cost DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    approved_by_dentist_id BIGINT NULL,
    approved_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    cancellation_reason VARCHAR(255) NULL,
    clinical_notes TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_treatment_plans_patient FOREIGN KEY (patient_id) REFERENCES users (id),
    CONSTRAINT fk_treatment_plans_dentist FOREIGN KEY (dentist_id) REFERENCES users (id),
    CONSTRAINT fk_treatment_plans_exam FOREIGN KEY (examination_id) REFERENCES clinical_examinations (id),
    CONSTRAINT fk_treatment_plans_created_by FOREIGN KEY (created_by_user_id) REFERENCES users (id),
    CONSTRAINT fk_treatment_plans_approved_by FOREIGN KEY (approved_by_dentist_id) REFERENCES users (id),
    CONSTRAINT chk_treatment_plans_status CHECK (status IN ('PROPOSED', 'APPROVED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT chk_treatment_plans_est_cost CHECK (total_estimated_cost >= 0.00),
    CONSTRAINT chk_treatment_plans_act_cost CHECK (total_actual_cost >= 0.00),
    KEY idx_treatment_plans_patient (patient_id),
    KEY idx_treatment_plans_dentist (dentist_id),
    KEY idx_treatment_plans_status (status),
    KEY idx_treatment_plans_exam (examination_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS treatment_procedures (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    treatment_plan_id BIGINT NOT NULL,
    tooth_number INT NULL,
    procedure_name VARCHAR(150) NOT NULL,
    procedure_code VARCHAR(50) NULL,
    sequence_number INT NOT NULL DEFAULT 1,
    status VARCHAR(30) NOT NULL DEFAULT 'PLANNED',
    estimated_cost DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    actual_cost DECIMAL(12, 2) NULL,
    completion_date DATE NULL,
    performed_by_dentist_id BIGINT NULL,
    assisted_by_user_id BIGINT NULL,
    clinical_progress_notes TEXT NULL,
    cancellation_reason VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_treatment_procedures_plan FOREIGN KEY (treatment_plan_id) REFERENCES treatment_plans (id),
    CONSTRAINT fk_treatment_procedures_performed_by FOREIGN KEY (performed_by_dentist_id) REFERENCES users (id),
    CONSTRAINT fk_treatment_procedures_assisted_by FOREIGN KEY (assisted_by_user_id) REFERENCES users (id),
    CONSTRAINT chk_treatment_procedures_status CHECK (status IN ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT chk_treatment_procedures_est_cost CHECK (estimated_cost >= 0.00),
    CONSTRAINT chk_treatment_procedures_act_cost CHECK (actual_cost IS NULL OR actual_cost >= 0.00),
    CONSTRAINT chk_treatment_procedures_completion CHECK (status != 'COMPLETED' OR completion_date IS NOT NULL),
    CONSTRAINT chk_treatment_procedures_fdi CHECK (tooth_number IS NULL OR tooth_number BETWEEN 11 AND 18 OR tooth_number BETWEEN 21 AND 28 OR tooth_number BETWEEN 31 AND 38 OR tooth_number BETWEEN 41 AND 48 OR tooth_number BETWEEN 51 AND 55 OR tooth_number BETWEEN 61 AND 65 OR tooth_number BETWEEN 71 AND 75 OR tooth_number BETWEEN 81 AND 85),
    KEY idx_treatment_procedures_plan (treatment_plan_id),
    KEY idx_treatment_procedures_status (status),
    KEY idx_treatment_procedures_tooth (tooth_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS clinical_progress_notes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    treatment_plan_id BIGINT NOT NULL,
    treatment_procedure_id BIGINT NULL,
    author_user_id BIGINT NOT NULL,
    note_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note_content TEXT NOT NULL,
    follow_up_date DATE NULL,
    CONSTRAINT fk_progress_notes_plan FOREIGN KEY (treatment_plan_id) REFERENCES treatment_plans (id),
    CONSTRAINT fk_progress_notes_procedure FOREIGN KEY (treatment_procedure_id) REFERENCES treatment_procedures (id),
    CONSTRAINT fk_progress_notes_author FOREIGN KEY (author_user_id) REFERENCES users (id),
    KEY idx_progress_notes_plan (treatment_plan_id),
    KEY idx_progress_notes_procedure (treatment_procedure_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS prescriptions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    dentist_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    notes TEXT,
    replaced_by_prescription_id BIGINT,
    finalized_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_prescriptions_patient FOREIGN KEY (patient_id) REFERENCES users (id),
    CONSTRAINT fk_prescriptions_dentist FOREIGN KEY (dentist_id) REFERENCES users (id),
    CONSTRAINT fk_prescriptions_replaced FOREIGN KEY (replaced_by_prescription_id) REFERENCES prescriptions (id),
    CONSTRAINT chk_prescriptions_status CHECK (status IN ('DRAFT', 'FINALIZED', 'CANCELLED')),
    KEY idx_prescriptions_patient (patient_id),
    KEY idx_prescriptions_dentist (dentist_id),
    KEY idx_prescriptions_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS prescription_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    prescription_id BIGINT NOT NULL,
    medicine_name VARCHAR(150) NOT NULL,
    strength VARCHAR(100),
    dosage VARCHAR(100) NOT NULL,
    frequency VARCHAR(100) NOT NULL,
    duration VARCHAR(100) NOT NULL,
    quantity INT NOT NULL,
    instructions TEXT,
    CONSTRAINT fk_prescription_items_prescription FOREIGN KEY (prescription_id) REFERENCES prescriptions (id) ON DELETE CASCADE,
    CONSTRAINT chk_prescription_items_qty CHECK (quantity > 0),
    KEY idx_prescription_items_prescription (prescription_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    invoice_number VARCHAR(50) NOT NULL,
    patient_id BIGINT NOT NULL,
    treatment_plan_id BIGINT,
    invoice_date DATE NOT NULL,
    subtotal DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    discount_amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    total_amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    paid_amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    balance_amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    status VARCHAR(20) NOT NULL,
    notes VARCHAR(500),
    issued_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT,
    CONSTRAINT uk_invoices_number UNIQUE (invoice_number),
    CONSTRAINT chk_invoices_subtotal CHECK (subtotal >= 0.00),
    CONSTRAINT chk_invoices_discount CHECK (discount_amount >= 0.00),
    CONSTRAINT chk_invoices_total CHECK (total_amount >= 0.00),
    CONSTRAINT chk_invoices_paid CHECK (paid_amount >= 0.00),
    CONSTRAINT chk_invoices_balance CHECK (balance_amount >= 0.00),
    CONSTRAINT chk_invoices_status CHECK (status IN ('DRAFT', 'UNPAID', 'PARTIALLY_PAID', 'PAID', 'CANCELLED')),
    KEY idx_invoices_patient (patient_id),
    KEY idx_invoices_date (invoice_date),
    KEY idx_invoices_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoice_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    invoice_id BIGINT NOT NULL,
    treatment_procedure_id BIGINT,
    description VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    line_total DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT fk_invoice_items_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE,
    CONSTRAINT chk_invoice_items_qty CHECK (quantity > 0),
    CONSTRAINT chk_invoice_items_price CHECK (unit_price >= 0.00),
    CONSTRAINT chk_invoice_items_total CHECK (line_total >= 0.00),
    KEY idx_invoice_items_invoice (invoice_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    invoice_id BIGINT NOT NULL,
    payment_number VARCHAR(50) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    payment_reference VARCHAR(100),
    paid_at TIMESTAMP NOT NULL,
    recorded_by BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'RECORDED',
    reversal_of_payment_id BIGINT,
    reversal_reason VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_payments_number UNIQUE (payment_number),
    CONSTRAINT fk_payments_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id),
    CONSTRAINT chk_payments_amount CHECK (amount > 0.00),
    CONSTRAINT chk_payments_method CHECK (payment_method IN ('CASH', 'CARD', 'BANK_TRANSFER', 'OTHER')),
    CONSTRAINT chk_payments_status CHECK (status IN ('RECORDED', 'REVERSED')),
    KEY idx_payments_invoice (invoice_id),
    KEY idx_payments_paid_at (paid_at),
    KEY idx_payments_recorded_by (recorded_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
